language: ruby
cache: bundler

rvm:
  - "2.3.0"

addons:
    postgresql: "9.3"

before_script:
    - psql -c 'create database chicago_transit_test;' -U postgres

script:
    - bundle exec rspec spec
    - bundle exec rubocop
    - bundle exec bundle-audit check --update
    - bundle exec brakeman -z

sudo: false
